name: Release Feature Branch Automatically
run-name: dp-dp-nxtleap-rebase
on:
    workflow_dispatch:
jobs:
    fetch-branches:
      runs-on: ubuntu-latest
      outputs:
        branches: ${{ steps.get-branches.outputs.branches }}
      
      steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              token: ${{ secrets.GITHUB_TOKEN }}

          - name: Get all the branches except default branch
            id: get-branches
            run: |
              DEFAULT_BRANCH=develop  # Replace with your default branch
              # DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
              echo "${DEFAULT_BRANCH}"
              BRANCHES=$(git branch -r | grep -vE "origin/(${DEFAULT_BRANCH}|main|HEAD)" | sed 's@^ *origin/@@')
              echo "${BRANCHES}"
              BRANCH_LIST=$(echo ${BRANCHES} | jq -R -s -c 'split("\n") | map(select(length > 0))')
              echo "${BRANCH_LIST}"
              echo "branches=${BRANCH_LIST}" >> "$GITHUB_OUTPUT"
              echo "${BRANCH_LIST}"

    rebase-branches:
      needs: fetch-branches
      runs-on: ubuntu-latest
      strategy:
        matrix:
          branch: ${{ fromJSON(needs.fetch-branches.outputs.branches) }}
          
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Print just names
          run:
            echo '${{ matrix.branches }}'


