name: Release Feature Branch Automatically
run-name: dp-dp-nxtleap-rebase
on:
    workflow_dispatch:
jobs:
    fetch-branches:
      runs-on: ubuntu-latest
      outputs:
        branches: ${{ steps.get-branches.outputs.branches }}
      
      steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              token: ${{ secrets.GITHUB_TOKEN }}

          - name: Update remote references and fetch
            run: |
              git remote set-head origin --auto
              git fetch --all --prune
        
          - name: List branches
            run: |
              git branch -r
      
          - name: Get all branches except develop and main
            id: get-branches
            run: |
              DEFAULT_BRANCH=develop 
              BRANCHES=$(git branch -r | grep -vE "origin/($DEFAULT_BRANCH|main|HEAD)" | sed 's@^ *origin/@@')
              echo "$BRANCHES" 
      
              if [ -z "$BRANCHES" ]; then
                echo "If No branches are found then exit."
                exit 1 
              fi

              BRANCH_SEPERATED=$(echo $BRANCHES | tr ' \n' ',' | sed 's/,$//')
              echo "$BRANCH_SEPERATED"
              BRANCH_LIST=$(echo $BRANCH_SEPERATED | jq -R -s -c 'split(",") | map(gsub("^[[:space:]]+|[[:space:]]+$";"")) | map(select(length > 0))' | sed 's/\\n//g')
              echo "Branches List: $BRANCH_LIST" 
              echo "branches=$BRANCH_LIST" >> $GITHUB_OUTPUT

    rebase-branches:
      needs: fetch-branches
      runs-on: ubuntu-latest
      strategy:
        matrix:
          branch: ${{ fromJSON(needs.fetch-branches.outputs.branches) }}
          
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Print just names
          run: |
            CURRENT_BRANCH=$(echo "${{ matrix.branch }}" | sed 's/[[:space:]]*$//')
            echo "Finding exact parent branch for $CURRENT_BRANCH..."

            # Function to find the closest parent branch
            find_parent_branch() {
              local current_branch=$1
              local potential_parents=($2)
              local best_parent=""
              local best_base=""
              local earliest_date=""

              for parent in "${potential_parents[@]}"; do
                merge_base=$(git merge-base "$current_branch" "$parent")
                
                if [ -z "$merge_base" ]; then
                  continue
                fi

                merge_base_date=$(git show -s --format=%ci "$merge_base")

                if [ -z "$earliest_date" ] || [[ "$merge_base_date" > "$earliest_date" ]]; then
                  best_parent="$parent"
                  best_base="$merge_base"
                  earliest_date="$merge_base_date"
                fi
              done

              if [ -n "$best_parent" ]; then
                echo "$best_parent"
              else
                echo "No parent branch found for $current_branch"
                exit 1
              fi
            }

            # Get the list of all branches except the current one
            POTENTIAL_PARENTS=$(git for-each-ref --format='%(refname:short)' refs/heads/ | grep -v "^$CURRENT_BRANCH$")
            
            # Convert potential parents to array
            POTENTIAL_PARENTS_ARRAY=($POTENTIAL_PARENTS)

            # Find the exact parent branch
            EXACT_PARENT_BRANCH=$(find_parent_branch "$CURRENT_BRANCH" "${POTENTIAL_PARENTS_ARRAY[@]}")
            echo "Exact parent branch for $CURRENT_BRANCH is $EXACT_PARENT_BRANCH"
            echo "parent_branch=$EXACT_PARENT_BRANCH" >> $GITHUB_ENV
# PARENT_BRANCH=$(git log --pretty=%P -n 1 origin/$BRANCH | awk '{print $1}')
# PARENT_BRANCH_NAME=$(git branch -r --contains $PARENT_BRANCH | grep -vE "origin/(${BRANCH}|develop|main)" | sed 's@^ *origin/@@' | head -n 1)

# echo "Detected parent branch for $BRANCH: $PARENT_BRANCH_NAME"

# 
# git checkout $BRANCH
# PARENT_BRANCH = $(git show-branch | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
# echo "parent_branch: $PARENT_BRANCH"


