name: Release Feature Branch Automatically
run-name: dp-dp-nxtleap-rebase
on:
    workflow_dispatch:
jobs:
    fetch-branches:
      runs-on: ubuntu-latest
      outputs:
        branches: ${{ steps.get-branches.output.branches }}
      
      steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              token: ${{ secrets.GITHUB_TOKEN }}

          - name: Get all branches except develop and main
            id: get-branches
            run: |
              DEFAULT_BRANCH=develop  # Replace with your default branch
              BRANCHES=$(git branch -r | grep -vE "origin/(${DEFAULT_BRANCH}|main)" | sed 's@^ *origin/@@')
              BRANCH_LIST=$(echo $BRANCHES | jq -R -s -c 'split("\n") | map(select(length > 0))')
              echo "Branches list: $BRANCH_LIST"  # Log for debugging
              echo "branches=$BRANCH_LIST" >> $GITHUB_ENV  # Set output using Environment File
        
          - name: Set output
            id: set-output
            run: |
              echo "branches=$(cat $GITHUB_ENV | grep 'branches=' | cut -d'=' -f2-)" >> $GITHUB_ENV

    rebase-branches:
      needs: fetch-branches
      runs-on: ubuntu-latest
      strategy:
        matrix:
          branch: ${{ fromJSON(needs.fetch-branches.outputs.branches) }}
          
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Print just names
          run: |
            echo '${{ matrix.branch }}'


