name: Release Feature Branch Automatically
run-name: dp-dp-nxtleap-rebase
on:
    workflow_dispatch:
jobs:
    fetch-branches:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Get all the branches except default branch
              id: get-branches
              run: |
                DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
                BRANCHES=$(git branch -r | grep -v $DEFAULT_BRANCH | sed 's@^ *origin/@@')
                echo "::set-output name=branches::$(echo $BRANCHES | tr '\n' ',')"
